services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: focusflow_user
      POSTGRES_PASSWORD: supersecurepassword
      POSTGRES_DB: focusflow_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  backend:
    build:
      context: ./backend
    command: npm run start
    ports:
      - "3000:3000"
    environment:
      DB_USER: focusflow_user
      DB_HOST: postgres
      DB_PASS: supersecurepassword
      DB_NAME: focusflow_db
    depends_on:
      - postgres
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build:
      context: ./app
    command: npx expo start --lan
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    depends_on:
      - backend
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  pgdata: